[ { source: '韦家碾', target: '升仙湖', lineStyle: { color: '#EE1822' } },
  { source: '升仙湖',
    target: '火车北站',
    lineStyle: { color: '#EE1822' } },
  { source: '火车北站',
    target: '人民北路',
    lineStyle: { color: '#EE1822' } },
  { source: '人民北路',
    target: '文殊院',
    lineStyle: { color: '#EE1822' } },
  { source: '文殊院', target: '骡马市', lineStyle: { color: '#EE1822' } },
  { source: '骡马市',
    target: '天府广场',
    lineStyle: { color: '#EE1822' } },
  { source: '天府广场',
    target: '锦江宾馆',
    lineStyle: { color: '#EE1822' } },
  { source: '锦江宾馆',
    target: '华西坝',
    lineStyle: { color: '#EE1822' } },
  { source: '华西坝',
    target: '省体育馆',
    lineStyle: { color: '#EE1822' } },
  { source: '省体育馆',
    target: '倪家桥',
    lineStyle: { color: '#EE1822' } },
  { source: '倪家桥', target: '桐梓林', lineStyle: { color: '#EE1822' } },
  { source: '桐梓林',
    target: '火车南站',
    lineStyle: { color: '#EE1822' } },
  { source: '火车南站', target: '高新', lineStyle: { color: '#EE1822' } },
  { source: '高新', target: '金融城', lineStyle: { color: '#EE1822' } },
  { source: '金融城', target: '孵化园', lineStyle: { color: '#EE1822' } },
  { source: '孵化园',
    target: '锦城广场',
    lineStyle: { color: '#EE1822' } },
  { source: '锦城广场',
    target: '世纪城',
    lineStyle: { color: '#EE1822' } },
  { source: '世纪城',
    target: '天府三街',
    lineStyle: { color: '#EE1822' } },
  { source: '天府三街',
    target: '天府五街',
    lineStyle: { color: '#EE1822' } },
  { source: '天府五街',
    target: '华府大道',
    lineStyle: { color: '#EE1822' } },
  { source: '华府大道', target: '四河', lineStyle: { color: '#EE1822' } },
  { source: '四河', target: '广都', lineStyle: { color: '#EE1822' } },
  { source: '广都', target: '五根松', lineStyle: { color: '#EE1822' } },
  { source: '韦家碾', target: '升仙湖', lineStyle: { color: '#EE1822' } },
  { source: '升仙湖',
    target: '火车北站',
    lineStyle: { color: '#EE1822' } },
  { source: '火车北站',
    target: '人民北路',
    lineStyle: { color: '#EE1822' } },
  { source: '人民北路',
    target: '文殊院',
    lineStyle: { color: '#EE1822' } },
  { source: '文殊院', target: '骡马市', lineStyle: { color: '#EE1822' } },
  { source: '骡马市',
    target: '天府广场',
    lineStyle: { color: '#EE1822' } },
  { source: '天府广场',
    target: '锦江宾馆',
    lineStyle: { color: '#EE1822' } },
  { source: '锦江宾馆',
    target: '华西坝',
    lineStyle: { color: '#EE1822' } },
  { source: '华西坝',
    target: '省体育馆',
    lineStyle: { color: '#EE1822' } },
  { source: '省体育馆',
    target: '倪家桥',
    lineStyle: { color: '#EE1822' } },
  { source: '倪家桥', target: '桐梓林', lineStyle: { color: '#EE1822' } },
  { source: '桐梓林',
    target: '火车南站',
    lineStyle: { color: '#EE1822' } },
  { source: '火车南站', target: '高新', lineStyle: { color: '#EE1822' } },
  { source: '高新', target: '金融城', lineStyle: { color: '#EE1822' } },
  { source: '金融城', target: '孵化园', lineStyle: { color: '#EE1822' } },
  { source: '孵化园',
    target: '锦城广场',
    lineStyle: { color: '#EE1822' } },
  { source: '锦城广场',
    target: '世纪城',
    lineStyle: { color: '#EE1822' } },
  { source: '世纪城',
    target: '天府三街',
    lineStyle: { color: '#EE1822' } },
  { source: '天府三街',
    target: '天府五街',
    lineStyle: { color: '#EE1822' } },
  { source: '天府五街',
    target: '华府大道',
    lineStyle: { color: '#EE1822' } },
  { source: '华府大道', target: '四河', lineStyle: { color: '#EE1822' } },
  { source: '四河', target: '华阳', lineStyle: { color: '#EE1822' } },
  { source: '华阳', target: '海昌路', lineStyle: { color: '#EE1822' } },
  { source: '海昌路', target: '广福', lineStyle: { color: '#EE1822' } },
  { source: '广福', target: '红石公园', lineStyle: { color: '#EE1822' } },
  { source: '红石公园', target: '麓湖', lineStyle: { color: '#EE1822' } },
  { source: '麓湖', target: '武汉路', lineStyle: { color: '#EE1822' } },
  { source: '武汉路',
    target: '天府公园',
    lineStyle: { color: '#EE1822' } },
  { source: '天府公园',
    target: '西博城',
    lineStyle: { color: '#EE1822' } },
  { source: '西博城', target: '广州路', lineStyle: { color: '#EE1822' } },
  { source: '广州路', target: '兴隆湖', lineStyle: { color: '#EE1822' } },
  { source: '兴隆湖', target: '科学城', lineStyle: { color: '#EE1822' } },
  { source: '犀浦', target: '天河路', lineStyle: { color: '#85C73F' } },
  { source: '天河路', target: '百草路', lineStyle: { color: '#85C73F' } },
  { source: '百草路', target: '金周路', lineStyle: { color: '#85C73F' } },
  { source: '金周路',
    target: '金科北路',
    lineStyle: { color: '#85C73F' } },
  { source: '金科北路',
    target: '迎宾大道',
    lineStyle: { color: '#85C73F' } },
  { source: '迎宾大道',
    target: '茶店子客运站',
    lineStyle: { color: '#85C73F' } },
  { source: '茶店子客运站',
    target: '羊犀立交',
    lineStyle: { color: '#85C73F' } },
  { source: '羊犀立交',
    target: '一品天下',
    lineStyle: { color: '#85C73F' } },
  { source: '一品天下',
    target: '蜀汉路东',
    lineStyle: { color: '#85C73F' } },
  { source: '蜀汉路东',
    target: '白果林',
    lineStyle: { color: '#85C73F' } },
  { source: '白果林',
    target: '中医大省医院',
    lineStyle: { color: '#85C73F' } },
  { source: '中医大省医院',
    target: '通惠门',
    lineStyle: { color: '#85C73F' } },
  { source: '通惠门',
    target: '人民公园',
    lineStyle: { color: '#85C73F' } },
  { source: '人民公园',
    target: '天府广场',
    lineStyle: { color: '#85C73F' } },
  { source: '天府广场',
    target: '春熙路',
    lineStyle: { color: '#85C73F' } },
  { source: '春熙路',
    target: '东门大桥',
    lineStyle: { color: '#85C73F' } },
  { source: '东门大桥',
    target: '牛王庙',
    lineStyle: { color: '#85C73F' } },
  { source: '牛王庙', target: '牛市口', lineStyle: { color: '#85C73F' } },
  { source: '牛市口', target: '东大路', lineStyle: { color: '#85C73F' } },
  { source: '东大路',
    target: '塔子山公园',
    lineStyle: { color: '#85C73F' } },
  { source: '塔子山公园',
    target: '成都东客站',
    lineStyle: { color: '#85C73F' } },
  { source: '成都东客站',
    target: '成渝立交',
    lineStyle: { color: '#85C73F' } },
  { source: '成渝立交',
    target: '惠王陵',
    lineStyle: { color: '#85C73F' } },
  { source: '惠王陵', target: '洪河', lineStyle: { color: '#85C73F' } },
  { source: '洪河',
    target: '成都行政学院',
    lineStyle: { color: '#85C73F' } },
  { source: '成都行政学院',
    target: '大面铺',
    lineStyle: { color: '#85C73F' } },
  { source: '大面铺', target: '连山坡', lineStyle: { color: '#85C73F' } },
  { source: '连山坡', target: '界牌', lineStyle: { color: '#85C73F' } },
  { source: '界牌', target: '书房', lineStyle: { color: '#85C73F' } },
  { source: '书房', target: '龙平路', lineStyle: { color: '#85C73F' } },
  { source: '龙平路', target: '龙泉驿', lineStyle: { color: '#85C73F' } },
  { source: '太平园', target: '红牌楼', lineStyle: { color: '#FDD303' } },
  { source: '红牌楼', target: '高升桥', lineStyle: { color: '#FDD303' } },
  { source: '高升桥', target: '衣冠庙', lineStyle: { color: '#FDD303' } },
  { source: '衣冠庙',
    target: '省体育馆',
    lineStyle: { color: '#FDD303' } },
  { source: '省体育馆',
    target: '磨子桥',
    lineStyle: { color: '#FDD303' } },
  { source: '磨子桥', target: '新南门', lineStyle: { color: '#FDD303' } },
  { source: '新南门', target: '春熙路', lineStyle: { color: '#FDD303' } },
  { source: '春熙路',
    target: '市二医院',
    lineStyle: { color: '#FDD303' } },
  { source: '市二医院',
    target: '红星桥',
    lineStyle: { color: '#FDD303' } },
  { source: '红星桥', target: '前锋路', lineStyle: { color: '#FDD303' } },
  { source: '前锋路', target: '李家沱', lineStyle: { color: '#FDD303' } },
  { source: '李家沱', target: '驷马桥', lineStyle: { color: '#FDD303' } },
  { source: '驷马桥',
    target: '昭觉寺南路',
    lineStyle: { color: '#FDD303' } },
  { source: '昭觉寺南路',
    target: '动物园',
    lineStyle: { color: '#FDD303' } },
  { source: '动物园',
    target: '熊猫大道',
    lineStyle: { color: '#FDD303' } },
  { source: '熊猫大道',
    target: '军区总医院',
    lineStyle: { color: '#FDD303' } },
  { source: '马厂坝',
    target: '凤凰大街',
    lineStyle: { color: '#4E2C8D' } },
  { source: '凤凰大街', target: '涌泉', lineStyle: { color: '#4E2C8D' } },
  { source: '涌泉', target: '光华公园', lineStyle: { color: '#4E2C8D' } },
  { source: '光华公园',
    target: '南熏大道',
    lineStyle: { color: '#4E2C8D' } },
  { source: '南熏大道',
    target: '凤溪河',
    lineStyle: { color: '#4E2C8D' } },
  { source: '凤溪河', target: '杨柳河', lineStyle: { color: '#4E2C8D' } },
  { source: '杨柳河', target: '万盛', lineStyle: { color: '#4E2C8D' } },
  { source: '万盛',
    target: '非遗博览园',
    lineStyle: { color: '#4E2C8D' } },
  { source: '非遗博览园',
    target: '蔡桥',
    lineStyle: { color: '#4E2C8D' } },
  { source: '蔡桥', target: '中坝', lineStyle: { color: '#4E2C8D' } },
  { source: '中坝', target: '成都西站', lineStyle: { color: '#4E2C8D' } },
  { source: '成都西站',
    target: '清江西路',
    lineStyle: { color: '#4E2C8D' } },
  { source: '清江西路',
    target: '文化宫',
    lineStyle: { color: '#4E2C8D' } },
  { source: '文化宫',
    target: '西南财大',
    lineStyle: { color: '#4E2C8D' } },
  { source: '西南财大',
    target: '草堂北路',
    lineStyle: { color: '#4E2C8D' } },
  { source: '草堂北路',
    target: '中医大省医院',
    lineStyle: { color: '#4E2C8D' } },
  { source: '中医大省医院',
    target: '宽窄巷子',
    lineStyle: { color: '#4E2C8D' } },
  { source: '宽窄巷子',
    target: '骡马市',
    lineStyle: { color: '#4E2C8D' } },
  { source: '骡马市',
    target: '太升南路',
    lineStyle: { color: '#4E2C8D' } },
  { source: '太升南路',
    target: '市二医院',
    lineStyle: { color: '#4E2C8D' } },
  { source: '市二医院',
    target: '玉双路',
    lineStyle: { color: '#4E2C8D' } },
  { source: '玉双路', target: '双桥路', lineStyle: { color: '#4E2C8D' } },
  { source: '双桥路', target: '万年场', lineStyle: { color: '#4E2C8D' } },
  { source: '万年场', target: '槐树店', lineStyle: { color: '#4E2C8D' } },
  { source: '槐树店', target: '来龙', lineStyle: { color: '#4E2C8D' } },
  { source: '来龙', target: '十陵', lineStyle: { color: '#4E2C8D' } },
  { source: '十陵', target: '成都大学', lineStyle: { color: '#4E2C8D' } },
  { source: '成都大学',
    target: '明蜀王陵',
    lineStyle: { color: '#4E2C8D' } },
  { source: '明蜀王陵', target: '西河', lineStyle: { color: '#4E2C8D' } },
  { source: '太平园', target: '簇锦', lineStyle: { color: '#B8A8CF' } },
  { source: '簇锦', target: '华兴', lineStyle: { color: '#B8A8CF' } },
  { source: '华兴', target: '金花', lineStyle: { color: '#B8A8CF' } },
  { source: '金花',
    target: '双流机场1航站楼',
    lineStyle: { color: '#B8A8CF' } },
  { source: '双流机场1航站楼',
    target: '双流机场2航站楼',
    lineStyle: { color: '#B8A8CF' } },
  { source: '高朋大道',
    target: '神仙树',
    lineStyle: { color: '#F26F1F' } },
  { source: '神仙树',
    target: '火车南站',
    lineStyle: { color: '#F26F1F' } },
  { source: '火车南站',
    target: '三瓦窑',
    lineStyle: { color: '#F26F1F' } },
  { source: '三瓦窑', target: '琉璃场', lineStyle: { color: '#F26F1F' } },
  { source: '琉璃场',
    target: '四川师大',
    lineStyle: { color: '#F26F1F' } },
  { source: '四川师大',
    target: '狮子山',
    lineStyle: { color: '#F26F1F' } },
  { source: '狮子山', target: '大观', lineStyle: { color: '#F26F1F' } },
  { source: '大观',
    target: '成都东客站',
    lineStyle: { color: '#F26F1F' } },
  { source: '成都东客站',
    target: '迎晖路',
    lineStyle: { color: '#F26F1F' } },
  { source: '迎晖路', target: '槐树店', lineStyle: { color: '#F26F1F' } },
  { source: '槐树店', target: '双店路', lineStyle: { color: '#F26F1F' } },
  { source: '双店路', target: '崔家店', lineStyle: { color: '#F26F1F' } },
  { source: '崔家店',
    target: '理工大学',
    lineStyle: { color: '#F26F1F' } },
  { source: '理工大学',
    target: '二仙桥',
    lineStyle: { color: '#F26F1F' } },
  { source: '二仙桥', target: '八里庄', lineStyle: { color: '#F26F1F' } },
  { source: '八里庄', target: '府青路', lineStyle: { color: '#F26F1F' } },
  { source: '府青路', target: '驷马桥', lineStyle: { color: '#F26F1F' } },
  { source: '驷马桥',
    target: '火车北站',
    lineStyle: { color: '#F26F1F' } },
  { source: '火车北站',
    target: '北站西二路',
    lineStyle: { color: '#F26F1F' } },
  { source: '北站西二路',
    target: '九里堤',
    lineStyle: { color: '#F26F1F' } },
  { source: '九里堤',
    target: '西南交大',
    lineStyle: { color: '#F26F1F' } },
  { source: '西南交大',
    target: '花照壁',
    lineStyle: { color: '#F26F1F' } },
  { source: '花照壁', target: '茶店子', lineStyle: { color: '#F26F1F' } },
  { source: '茶店子',
    target: '一品天下',
    lineStyle: { color: '#F26F1F' } },
  { source: '一品天下',
    target: '金沙博物馆',
    lineStyle: { color: '#F26F1F' } },
  { source: '金沙博物馆',
    target: '文化宫',
    lineStyle: { color: '#F26F1F' } },
  { source: '文化宫', target: '东坡路', lineStyle: { color: '#F26F1F' } },
  { source: '东坡路', target: '龙爪堰', lineStyle: { color: '#F26F1F' } },
  { source: '龙爪堰',
    target: '武侯大道',
    lineStyle: { color: '#F26F1F' } },
  { source: '武侯大道',
    target: '太平园',
    lineStyle: { color: '#F26F1F' } } ]