[ { name: '韦家碾',
    x: 109.55,
    y: -769.35,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '升仙湖',
    x: 109.55,
    y: -669.35,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '火车北站',
    x: -28.95,
    y: -522.6,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '人民北路',
    x: -28.95,
    y: -411.6,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '文殊院',
    x: -96.55,
    y: -314.6,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '骡马市',
    x: -170.8,
    y: -240.6,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '天府广场',
    x: -170.8,
    y: -170.5,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '锦江宾馆',
    x: -170.8,
    y: -78.5,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '华西坝',
    x: -170.8,
    y: -5.95,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '省体育馆',
    x: -170.8,
    y: 69,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '倪家桥',
    x: -170.8,
    y: 120.15,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '桐梓林',
    x: -170.8,
    y: 181.7,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '火车南站',
    x: -170.8,
    y: 238.6,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '高新',
    x: -229.85,
    y: 380,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '金融城',
    x: -229.85,
    y: 453,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '孵化园',
    x: -229.85,
    y: 515.25,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '锦城广场',
    x: -195.85,
    y: 585.25,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '世纪城',
    x: -161.85,
    y: 645.5,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '天府三街',
    x: -161.85,
    y: 720,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '天府五街',
    x: -161.85,
    y: 795,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '华府大道',
    x: -161.85,
    y: 870,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '四河',
    x: -161.85,
    y: 945,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '广都',
    x: -121.85,
    y: 978,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '五根松',
    x: -81.85,
    y: 1018,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '华阳',
    x: -161.85,
    y: 1018,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '海昌路',
    x: -161.85,
    y: 1068,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '广福',
    x: -161.85,
    y: 1118,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '红石公园',
    x: -161.85,
    y: 1168,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '麓湖',
    x: -161.85,
    y: 1218,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '武汉路',
    x: -161.85,
    y: 1268,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '天府公园',
    x: -161.85,
    y: 1318,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '西博城',
    x: -161.85,
    y: 1368,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '广州路',
    x: -161.85,
    y: 1418,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '兴隆湖',
    x: -161.85,
    y: 1468,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '科学城',
    x: -161.85,
    y: 1518,
    itemStyle: { borderColor: '#EE1822', color: 'white' },
    category: '1号线' },
  { name: '犀浦',
    x: -785.35,
    y: -965,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '天河路',
    x: -745.35,
    y: -915,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '百草路',
    x: -705.35,
    y: -865,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '金周路',
    x: -665.35,
    y: -815,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '金科北路',
    x: -620.35,
    y: -765,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '迎宾大道',
    x: -580.35,
    y: -715,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '茶店子客运站',
    x: -540.35,
    y: -660,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '羊犀立交',
    x: -591.35,
    y: -516.3,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '一品天下',
    x: -529.6,
    y: -452.7,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '蜀汉路东',
    x: -453.8,
    y: -370,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '白果林',
    x: -398.2,
    y: -308.45,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '中医大省医院',
    x: -352.5,
    y: -258.95,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '通惠门',
    x: -287.85,
    y: -207.25,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '人民公园',
    x: -224.5,
    y: -188.6,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '春熙路',
    x: -34,
    y: -140,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '东门大桥',
    x: 35.5,
    y: -124.6,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '牛王庙',
    x: 113.5,
    y: -104.1,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '牛市口',
    x: 196.15,
    y: -82.6,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '东大路',
    x: 227.7,
    y: -62.95,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '塔子山公园',
    x: 270.7,
    y: -44.65,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '成都东客站',
    x: 318.7,
    y: -44.2,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '成渝立交',
    x: 359.2,
    y: 5.8,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '惠王陵',
    x: 434.7,
    y: 97.8,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '洪河',
    x: 474.7,
    y: 147,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '成都行政学院',
    x: 519.7,
    y: 200,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '大面铺',
    x: 582.7,
    y: 200,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '连山坡',
    x: 648.7,
    y: 200,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '界牌',
    x: 715.7,
    y: 200,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '书房',
    x: 784.7,
    y: 200,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '龙平路',
    x: 850.7,
    y: 200,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '龙泉驿',
    x: 918.7,
    y: 200,
    itemStyle: { borderColor: '#85C73F', color: 'white' },
    category: '2号线' },
  { name: '太平园',
    x: -528,
    y: 238.6,
    itemStyle: { borderColor: '#FDD303', color: 'white' },
    category: '3号线' },
  { name: '红牌楼',
    x: -430,
    y: 69,
    itemStyle: { borderColor: '#FDD303', color: 'white' },
    category: '3号线' },
  { name: '高升桥',
    x: -345,
    y: 69,
    itemStyle: { borderColor: '#FDD303', color: 'white' },
    category: '3号线' },
  { name: '衣冠庙',
    x: -239,
    y: 69,
    itemStyle: { borderColor: '#FDD303', color: 'white' },
    category: '3号线' },
  { name: '磨子桥',
    x: -34,
    y: 69,
    itemStyle: { borderColor: '#FDD303', color: 'white' },
    category: '3号线' },
  { name: '新南门',
    x: -34,
    y: -62,
    itemStyle: { borderColor: '#FDD303', color: 'white' },
    category: '3号线' },
  { name: '市二医院',
    x: 2,
    y: -193,
    itemStyle: { borderColor: '#FDD303', color: 'white' },
    category: '3号线' },
  { name: '红星桥',
    x: 66,
    y: -290,
    itemStyle: { borderColor: '#FDD303', color: 'white' },
    category: '3号线' },
  { name: '前锋路',
    x: 123,
    y: -377,
    itemStyle: { borderColor: '#FDD303', color: 'white' },
    category: '3号线' },
  { name: '李家沱',
    x: 124,
    y: -444,
    itemStyle: { borderColor: '#FDD303', color: 'white' },
    category: '3号线' },
  { name: '驷马桥',
    x: 195,
    y: -524,
    itemStyle: { borderColor: '#FDD303', color: 'white' },
    category: '3号线' },
  { name: '昭觉寺南路',
    x: 242,
    y: -575,
    itemStyle: { borderColor: '#FDD303', color: 'white' },
    category: '3号线' },
  { name: '动物园',
    x: 292,
    y: -632,
    itemStyle: { borderColor: '#FDD303', color: 'white' },
    category: '3号线' },
  { name: '熊猫大道',
    x: 340,
    y: -686,
    itemStyle: { borderColor: '#FDD303', color: 'white' },
    category: '3号线' },
  { name: '军区总医院',
    x: 389,
    y: -742,
    itemStyle: { borderColor: '#FDD303', color: 'white' },
    category: '3号线' },
  { name: '马厂坝',
    x: -894.5,
    y: -260.7,
    itemStyle: { borderColor: '#4E2C8D', color: 'white' },
    category: '4号线' },
  { name: '凤凰大街',
    x: -975.5,
    y: -260.7,
    itemStyle: { borderColor: '#4E2C8D', color: 'white' },
    category: '4号线' },
  { name: '涌泉',
    x: -1045.5,
    y: -260.7,
    itemStyle: { borderColor: '#4E2C8D', color: 'white' },
    category: '4号线' },
  { name: '光华公园',
    x: -1106.5,
    y: -260.7,
    itemStyle: { borderColor: '#4E2C8D', color: 'white' },
    category: '4号线' },
  { name: '南熏大道',
    x: -1170.5,
    y: -260.7,
    itemStyle: { borderColor: '#4E2C8D', color: 'white' },
    category: '4号线' },
  { name: '凤溪河',
    x: -1236.5,
    y: -260.7,
    itemStyle: { borderColor: '#4E2C8D', color: 'white' },
    category: '4号线' },
  { name: '杨柳河',
    x: -1299.5,
    y: -260.7,
    itemStyle: { borderColor: '#4E2C8D', color: 'white' },
    category: '4号线' },
  { name: '万盛',
    x: -1368.5,
    y: -260.7,
    itemStyle: { borderColor: '#4E2C8D', color: 'white' },
    category: '4号线' },
  { name: '非遗博览园',
    x: -820,
    y: -262,
    itemStyle: { borderColor: '#4E2C8D', color: 'white' },
    category: '4号线' },
  { name: '蔡桥',
    x: -724,
    y: -262,
    itemStyle: { borderColor: '#4E2C8D', color: 'white' },
    category: '4号线' },
  { name: '中坝',
    x: -664,
    y: -262,
    itemStyle: { borderColor: '#4E2C8D', color: 'white' },
    category: '4号线' },
  { name: '成都西站',
    x: -604,
    y: -261,
    itemStyle: { borderColor: '#4E2C8D', color: 'white' },
    category: '4号线' },
  { name: '清江西路',
    x: -560,
    y: -260,
    itemStyle: { borderColor: '#4E2C8D', color: 'white' },
    category: '4号线' },
  { name: '文化宫',
    x: -530,
    y: -260,
    itemStyle: { borderColor: '#4E2C8D', color: 'white' },
    category: '4号线' },
  { name: '西南财大',
    x: -456.5,
    y: -260,
    itemStyle: { borderColor: '#4E2C8D', color: 'white' },
    category: '4号线' },
  { name: '草堂北路',
    x: -394.5,
    y: -259,
    itemStyle: { borderColor: '#4E2C8D', color: 'white' },
    category: '4号线' },
  { name: '宽窄巷子',
    x: -258,
    y: -242,
    itemStyle: { borderColor: '#4E2C8D', color: 'white' },
    category: '4号线' },
  { name: '太升南路',
    x: -82,
    y: -216,
    itemStyle: { borderColor: '#4E2C8D', color: 'white' },
    category: '4号线' },
  { name: '玉双路',
    x: 124,
    y: -160,
    itemStyle: { borderColor: '#4E2C8D', color: 'white' },
    category: '4号线' },
  { name: '双桥路',
    x: 192,
    y: -141,
    itemStyle: { borderColor: '#4E2C8D', color: 'white' },
    category: '4号线' },
  { name: '万年场',
    x: 255,
    y: -131,
    itemStyle: { borderColor: '#4E2C8D', color: 'white' },
    category: '4号线' },
  { name: '槐树店',
    x: 319.2,
    y: -110.8,
    itemStyle: { borderColor: '#4E2C8D', color: 'white' },
    category: '4号线' },
  { name: '来龙',
    x: 480.2,
    y: -98.8,
    itemStyle: { borderColor: '#4E2C8D', color: 'white' },
    category: '4号线' },
  { name: '十陵',
    x: 552.2,
    y: -97.8,
    itemStyle: { borderColor: '#4E2C8D', color: 'white' },
    category: '4号线' },
  { name: '成都大学',
    x: 621.2,
    y: -97.8,
    itemStyle: { borderColor: '#4E2C8D', color: 'white' },
    category: '4号线' },
  { name: '明蜀王陵',
    x: 683.2,
    y: -97.8,
    itemStyle: { borderColor: '#4E2C8D', color: 'white' },
    category: '4号线' },
  { name: '西河',
    x: 745.2,
    y: -97.8,
    itemStyle: { borderColor: '#4E2C8D', color: 'white' },
    category: '4号线' },
  { name: '簇锦',
    x: -580.6,
    y: 333.9,
    itemStyle: { borderColor: '#B8A8CF', color: 'white' },
    category: '10号线' },
  { name: '华兴',
    x: -624.6,
    y: 408.9,
    itemStyle: { borderColor: '#B8A8CF', color: 'white' },
    category: '10号线' },
  { name: '金花',
    x: -731.1,
    y: 482.4,
    itemStyle: { borderColor: '#B8A8CF', color: 'white' },
    category: '10号线' },
  { name: '双流机场1航站楼',
    x: -839.6,
    y: 562,
    itemStyle: { borderColor: '#B8A8CF', color: 'white' },
    category: '10号线' },
  { name: '双流机场2航站楼',
    x: -882.9,
    y: 654.2,
    itemStyle: { borderColor: '#B8A8CF', color: 'white' },
    category: '10号线' },
  { name: '高朋大道',
    x: -445.8,
    y: 238.6,
    itemStyle: { borderColor: '#F26F1F', color: 'white' },
    category: '7号线' },
  { name: '神仙树',
    x: -353.5,
    y: 238.6,
    itemStyle: { borderColor: '#F26F1F', color: 'white' },
    category: '7号线' },
  { name: '三瓦窑',
    x: -52.3,
    y: 238.6,
    itemStyle: { borderColor: '#F26F1F', color: 'white' },
    category: '7号线' },
  { name: '琉璃场',
    x: 56.7,
    y: 184.9,
    itemStyle: { borderColor: '#F26F1F', color: 'white' },
    category: '7号线' },
  { name: '四川师大',
    x: 176.3,
    y: 128.6,
    itemStyle: { borderColor: '#F26F1F', color: 'white' },
    category: '7号线' },
  { name: '狮子山',
    x: 258.6,
    y: 88.4,
    itemStyle: { borderColor: '#F26F1F', color: 'white' },
    category: '7号线' },
  { name: '大观',
    x: 318.4,
    y: 59.7,
    itemStyle: { borderColor: '#F26F1F', color: 'white' },
    category: '7号线' },
  { name: '迎晖路',
    x: 319.3,
    y: -80.6,
    itemStyle: { borderColor: '#F26F1F', color: 'white' },
    category: '7号线' },
  { name: '双店路',
    x: 319.6,
    y: -201.9,
    itemStyle: { borderColor: '#F26F1F', color: 'white' },
    category: '7号线' },
  { name: '崔家店',
    x: 319.6,
    y: -288.9,
    itemStyle: { borderColor: '#F26F1F', color: 'white' },
    category: '7号线' },
  { name: '理工大学',
    x: 318.6,
    y: -368.7,
    itemStyle: { borderColor: '#F26F1F', color: 'white' },
    category: '7号线' },
  { name: '二仙桥',
    x: 318.6,
    y: -453.4,
    itemStyle: { borderColor: '#F26F1F', color: 'white' },
    category: '7号线' },
  { name: '八里庄',
    x: 318.1,
    y: -522.3,
    itemStyle: { borderColor: '#F26F1F', color: 'white' },
    category: '7号线' },
  { name: '府青路',
    x: 254.2,
    y: -522.3,
    itemStyle: { borderColor: '#F26F1F', color: 'white' },
    category: '7号线' },
  { name: '北站西二路',
    x: -92.3,
    y: -523,
    itemStyle: { borderColor: '#F26F1F', color: 'white' },
    category: '7号线' },
  { name: '九里堤',
    x: -173.6,
    y: -523.3,
    itemStyle: { borderColor: '#F26F1F', color: 'white' },
    category: '7号线' },
  { name: '西南交大',
    x: -258.5,
    y: -523.3,
    itemStyle: { borderColor: '#F26F1F', color: 'white' },
    category: '7号线' },
  { name: '花照壁',
    x: -335.1,
    y: -523.3,
    itemStyle: { borderColor: '#F26F1F', color: 'white' },
    category: '7号线' },
  { name: '茶店子',
    x: -409.6,
    y: -523.7,
    itemStyle: { borderColor: '#F26F1F', color: 'white' },
    category: '7号线' },
  { name: '金沙博物馆',
    x: -529.8,
    y: -349.9,
    itemStyle: { borderColor: '#F26F1F', color: 'white' },
    category: '7号线' },
  { name: '东坡路',
    x: -529.7,
    y: -150.3,
    itemStyle: { borderColor: '#F26F1F', color: 'white' },
    category: '7号线' },
  { name: '龙爪堰',
    x: -529.7,
    y: -43.3,
    itemStyle: { borderColor: '#F26F1F', color: 'white' },
    category: '7号线' },
  { name: '武侯大道',
    x: -529.7,
    y: 75.6,
    itemStyle: { borderColor: '#F26F1F', color: 'white' },
    category: '7号线' } ]